#!/bin/bash

# UEMS V18.3.1
if [ -f /awips2/uems/etc/EMS.profile ]; then
	. /awips2/uems/etc/EMS.profile
fi

NX=101
NY=155
DX=8000
DY=8000

ymd=20180324
cycle=00
ymdh=$ymd$cycle

run_name=${ymdh}_12km_co
nmm=nmm_co
domain=colorado

cd $EMS_DATA/domains/$domain

LAT="40.035"
LON="-105.2436"

# added -m flag to prevent gridgem_model.exe from recreating static file
#$WRF/etc/window_domain_rt.pl \
#	-w wrfsi.rotlat \
#	-s $DATA_SI \
#	-i $WRF \
#	-d $DATAROOT/${DOMAIN_NAME} \
#	-t $DATA_DOMS/colorado \
#	-m
# now copy over static netCDF file
#cp -r $DATAROOT/colorado/static/static.wrfsi.rotlat $DATAROOT/${DOMAIN_NAME}/static/
#wrf_prep --sfcdset ssthr --dset gfsgrb2 --ftp ncep --cycle ${CYCLE}:0:30
#set STATUS_PREP=$status
#if ( $STATUS_PREP == 0 ) then
#   # copy the ssthr data set
#   SSTHR=rtgssthr_grb_0.083
#   SAVDIR=$UEMS/data/grib/ssthr
#   if ( ! -e $SAVDIR ) mkdir -p $SAVDIR
#   if ( -e grib/${SSTHR} ) then
#      if ( -e ${SAVDIR}/${SSTHR} ) then
#         cmp -s grib/${SSTHR} ${SAVDIR}/${SSTHR}
#         set ISDIF=$status
#         if ( $ISDIF != 0 ) cp -p grib/${SSTHR} ${SAVDIR}/${SSTHR}
#      else
#         cp -p grib/${SSTHR} ${SAVDIR}/${SSTHR}
#      endif
#   endif
#else
#   sleep 300
#endif
